kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
  namespace: pacman
  labels:
     app: pacman
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
